name = "secondsight"
version = "0.0.1"
authors = ["Dan Lidral-Porter <dlp@aperiodic.org>"]

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"
branch = "class_hint"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[[bin]]
name = "secondsight"
